Repository microsoft/service-fabric, pull requests merged in 2018-03, with the labels that each got.

#12 Removed compression libraries previously required by the RocksDB
  Dockerfile
  src/prod/linuxsetup/debian/runtime/control/control.template
  src/prod/shared/ktlwf/logger/com/dll/CMakeLists.txt
  src/prod/src/Common/lib/CMakeLists.txt
  src/prod/src/Hosting2/test/CMakeLists.txt
  src/prod/src/Management/DnsService/test/CMakeLists.txt
  src/prod/src/Naming/test/CMakeLists.txt
  src/prod/src/Reliability/Failover/fm/test/CMakeLists.txt
  src/prod/src/Reliability/Failover/ra/test/CMakeLists.txt
  src/prod/src/data/interop/ReliableCollectionRuntime/dll/CMakeLists.txt
  src/prod/src/data/interop/ReliableCollectionService/dll/CMakeLists.txt
  src/prod/src/data/interop/ReliableCollectionServiceStandalone/dll/CMakeLists.txt
  src/prod/src/data/txnreplicator/loggingreplicator/test/CMakeLists.txt
  src/prod/src/linux/dockers/azure-service-fabric/setup.sh
  src/prod/src/retail/native/FabricGateway/exe/CMakeLists.txt
  src/prod/src/retail/native/FabricRuntime/dll/CMakeLists.txt
  src/prod/src/retail/native/FabricService/exe/CMakeLists.txt
  src/prod/src/retail/native/FabricServiceCommunication/CMakeLists.txt
  src/prod/src/retail/native/FabricTransport/CMakeLists.txt
  src/prod/src/retail/native/fabrichost/exe/CMakeLists.txt
  src/prod/test/FabricTest/TestHostExe/CMakeLists.txt
  src/prod/test/FabricTest/test/CMakeLists.txt
  src/prod/test/LinuxRetailTests/bin/CMakeLists.txt
Labels: Repo transition

#23 Fix intitial paragraph description
  README.md
Labels: Repo transition

#15 Adding a basic end-to-end test using a onebox cluster
  README.md
  docs/cluster_deployer_test.md
  src/prod/linuxsetup/CMakeLists.txt
  src/prod/src/linux/dockers/cluster-deployer/ClusterManifest.SingleMachineFSS.xml
  src/prod/src/linux/dockers/cluster-deployer/Dockerfile
  src/prod/src/linux/dockers/cluster-deployer/run.sh
  src/prod/src/linux/dockers/cluster-deployer/setup.sh
  src/test/ClusterDeployer/cluster.sh
  src/test/ClusterDeployer/image/ClusterManifest.SingleMachineFSS.xml
  src/test/ClusterDeployer/image/Dockerfile
  src/test/ClusterDeployer/image/run.sh
  src/test/ClusterDeployer/image/setup.sh
  src/test/ClusterDeployer/runtest.sh
  src/test/ClusterDeployer/test.sh
Labels: Repo transition

#35 Logic to check and pull from hub with fallback to local build, bump version
  DOCKER_VERSION
  runbuild.sh
Labels: enhancement

#67 Fixing documentation for the Cluster Deployer test
  docs/cluster_deployer_test.md
Labels: bug
